export const stages = [
  {id:'foundation',name:'30–20 kyu',focus:'Khí, bắt quân, luật và đếm diện tích',practice:'Chơi 3 ván 9×9. Sau mỗi ván, ghi lại một nhóm mất quân vì thiếu khí.'},
  {id:'tactics',name:'20–10 kyu',focus:'Đọc hai nước đen, nối/cắt và hình cờ',practice:'Chơi 3 ván 13×13 hoặc 19×19. Xem lại các điểm cắt và nhóm chỉ còn một khí.'},
  {id:'reading',name:'10–5 kyu',focus:'Đọc nhiều đáp trả, hướng chơi và sống/chết',practice:'Chơi 5 ván 19×19 với đối thủ có hạng. Chọn hai quyết định sai mỗi ván để tự đọc lại.'},
  {id:'strategy',name:'5–1 kyu',focus:'Tấn công, ko, quan tử và lựa chọn toàn bàn',practice:'Chơi 5 ván 19×19. Nhờ người mạnh hơn hoặc công cụ phân tích xem lại nhóm yếu và các nước quan tử lớn.'},
  {id:'dan',name:'Mục tiêu 1 dan',focus:'Đọc sâu và kiểm tra quyết định dưới áp lực',practice:'Duy trì thực chiến 19×19 với đối thủ có rating ổn định. Theo dõi kết quả và nhờ người mạnh hơn kiểm tra các ván. Hoàn thành bài tập không tự xác nhận 1 dan.'}
];
const letters='ABCDEFGHJKLMNOPQRST';
function diagram(size, black=[], white=[]) {
  const point = coordinate => (size-Number(coordinate.slice(1)))*size+letters.indexOf(coordinate[0]);
  return {size,setup:[...black.map(c=>[point(c),1]),...white.map(c=>[point(c),2])]};
}
const opening=diagram(19,['D4','Q16'],['Q4','D16']);
const flank=diagram(19,['D4','F4','Q16'],['D16','Q4','Q10']);
const middle=diagram(19,['D4','F4','F6','D16'],['G4','G5','Q4','Q16']);
const questions=[];
function q(stage,id,topic,title,prompt,choices,answer,explanation,position={size:0,setup:[]}) {
  questions.push({id:`q-${id}`,stage,topic,title,prompt,choices,answer,explanation,kind:'quiz',...position});
}
q('foundation','diagonal','Khí','Nối chéo có chia sẻ khí?','Hai quân cùng màu chỉ chạm chéo, không có quân nối ngang/dọc. Chúng là một nhóm chưa?',['Đã là một nhóm','Vẫn là hai nhóm'],1,'Chỉ kết nối ngang và dọc tạo thành nhóm. Liên kết chéo có thể bị cắt.',diagram(5,['B3','C2']));
q('foundation','corner-liberties','Khí','Khí ở góc','Một quân ở A5 trên bàn 5×5 trống có bao nhiêu khí?',['1','2','3','4'],1,'Chỉ có B5 và A4; biên bàn không phải giao điểm trống.',diagram(5,['A5']));
q('foundation','edge-liberties','Khí','Khí ở biên','Một quân ở C5 trên bàn trống có bao nhiêu khí?',['2','3','4'],1,'B5, D5, C4: 3 khí. Không có giao điểm phía ngoài bàn.',diagram(5,['C5']));
q('foundation','capture-order','Luật','Thứ tự khi đặt quân','Một nước đen lấp hết khí của nhóm trắng, đồng thời điểm đen đặt ban đầu chưa có khí. Phải kiểm tra gì trước?',['Bắt nhóm trắng hết khí, rồi kiểm tra khí đen','Cấm nước đi ngay vì ban đầu chưa có khí'],0,'Bắt các nhóm đối phương hết khí trước. Nếu sau khi nhấc trắng, nhóm đen có khí, nước đi có thể hợp lệ; vẫn phải kiểm tra lặp thế.');
q('foundation','area-captures','Đếm điểm','Quân đã bắt có cộng riêng?','Trong cách đếm diện tích của app, điểm bằng quân trên bàn cộng đất. Có cộng thêm số quân đã bắt vào điểm này không?',['Có','Không'],1,'Không cộng riêng tù binh trong cách đếm diện tích. Đừng trộn cách đếm đất với cách đếm diện tích.');
q('foundation','area-total','Đếm điểm','Một phép đếm nhỏ','Cuối ván: đen có 12 quân sống và 9 điểm đất, trắng có 10 quân sống và 8 điểm đất. Komi 6,5 cho trắng. Ai hơn?',['Đen hơn 3','Trắng hơn 3,5','Hòa'],1,'Đen = 12 + 9 = 21. Trắng = 10 + 8 + 6,5 = 24,5. Trắng hơn 3,5.');
q('foundation','neutral','Đếm điểm','Vùng giáp cả hai màu','Một vùng trống liên thông chỉ giáp cả quân đen lẫn quân trắng. Với cách đếm diện tích hiện tại, vùng này thuộc ai?',['Đen','Trắng','Không bên nào'],2,'Vùng giáp hai màu là vùng trung lập trong phép đếm vùng của app. Điều này không tự giải quyết quân chết.');
q('foundation','pass','Luật','Kết thúc ván luyện','Hai bên bỏ lượt liên tiếp. Có thể kết luận bộ đếm hiện tại đã phân xử đúng mọi quân chết chưa?',['Có, bỏ lượt tự xác nhận mọi nhóm sống','Chưa, cần xử lý quân chết hoặc chơi tiếp'],1,'Hai lượt bỏ kết thúc ván, nhưng thuật toán hiện tại không tự phân xử sống/chết. Chơi tiếp để bắt quân chết hoặc nhờ phân xử.');

q('tactics','shared','Khí','Khí chung chỉ đếm một lần','Hai quân đen B3 và C3 đứng cạnh nhau trên bàn trống. Cả nhóm có bao nhiêu khí?',['4','5','6','8'],2,'A3, B4, B2, D3, C4, C2: 6 điểm khác nhau.',diagram(5,['B3','C3']));
q('tactics','self-atari','Hình cờ','Nhận diện tự atari','Sau một nước hợp lệ, nhóm vừa đi chỉ còn một khí. Nếu không có lý do hy sinh hay bắt quân, cần kiểm tra điều gì?',['Nguy cơ đối phương bắt ở khí cuối','Chỉ số quân vừa nối được'],0,'Hợp lệ không đồng nghĩa an toàn. Tự atari cần được đọc đến nước bắt của đối phương.');
q('tactics','two-eyes','Sống/chết','Một khoảng trống lớn','Một nhóm bao quanh hai điểm trống liền nhau. Có chắc đã có hai mắt riêng không?',['Có, hai điểm là hai mắt','Không, đó có thể chỉ là một không gian mắt'],1,'Hai mắt phải là hai vùng riêng có khả năng bảo vệ nhóm. Số điểm trống không bằng số mắt.');
q('tactics','double-atari','Chiến thuật','Atari kép chưa phải kết luận','Một nước đưa hai nhóm địch vào atari. Để kết luận sẽ bắt được ít nhất một nhóm, còn phải kiểm tra gì?',['Địch có nước bắt, nối hoặc cứu đồng thời không','Không cần đọc thêm'],0,'Atari kép tạo hai đe dọa, nhưng phản công hoặc nối nhóm có thể hóa giải cả hai.');
q('tactics','ladder','Đọc biến','Trước khi đuổi thang','Một chuỗi atari dự kiến chạy chéo qua bàn. Điều gì phải kiểm tra ngoài vài nước đầu?',['Các quân nằm trên đường thang và điểm kết thúc','Chỉ khí của quân đầu tiên'],0,'Quân phá thang ở xa có thể giúp nhóm bị đuổi nối ra ngoài. Đọc tới điểm kết thúc hoặc tới kết nối an toàn.',opening);
q('tactics','net','Đọc biến','Lưới và atari','Có thể dùng một nước không atari để chặn mọi đường thoát của nhóm địch không?',['Không, phải atari ở mọi nước','Có, đó là ý tưởng của lưới'],1,'Lưới có thể bắt bằng chặn lối thoát, thay vì ép theo một chuỗi atari. Phải kiểm tra các đường xuyên lưới.');
q('tactics','snapback','Chiến thuật','Bắt lại sau hy sinh','Đen hy sinh một quân, trắng bắt, rồi đen bắt ngược ba quân trắng. Thế bàn mới khác mọi thế trước. Có bị cấm chỉ vì bắt lại ngay không?',['Có, mọi bắt lại ngay là ko','Không; vẫn kiểm tra tự sát và lịch sử thế bàn'],1,'Bắt lại ngay không tự động là ko. Snapback lấy nhóm lớn hơn và có thể tạo một thế hoàn toàn khác.');
q('tactics','corner-efficiency','Toàn bàn','Đất và biên bàn','Trên bàn 19×19 trống, nếu mục tiêu là bao vùng nhỏ bằng ít đường rào nhất, góc có lợi thế gì?',['Hai cạnh bàn làm sẵn một phần ranh giới','Góc được nhân đôi điểm'],0,'Hai cạnh giúp giảm số phía phải bao. Đây là lý do hình học, không phải quy tắc mọi nước khai cuộc đều ở góc.',{size:19,setup:[]});

q('reading','race','Đọc biến','Đua bắt đơn giản','Giả định hai nhóm không mắt, không khí chung, không nối/ko/throw-in; đen có 3 khí ngoài, trắng có 2. Hai bên chỉ lần lượt lấp khí đối phương, đen đi trước. Ai bắt trước?',['Đen','Trắng','Chắc chắn seki'],0,'Đen lấp 1, trắng lấp 1, đen lấp khí cuối của trắng và bắt. Các giả định đã loại bỏ những trường hợp làm công thức đếm khí sai.');
q('reading','shared-race','Đọc biến','Khi không dùng phép trừ khí','Hai nhóm có khí chung và một bên có mắt. Có nên chỉ lấy số khí ngoài trừ nhau để kết luận không?',['Có, luôn đúng','Không, phải đọc thứ tự lấp khí và mắt'],1,'Khí chung, mắt, nối, ko và nước hy sinh thay đổi thứ tự bắt. Phép đếm đơn giản cần đúng điều kiện áp dụng.');
q('reading','ladder-breaker','Đọc biến','Quân phá thang thay đổi','Biến thang lúc đầu bắt được. Đối phương vừa đặt thêm một quân đúng đường chạy của thang. Lần tới bạn có thể dùng nguyên kết luận cũ không?',['Có, thang đã được chứng minh','Không, phải đọc lại tới quân mới'],1,'Kết quả đọc thuộc một thế bàn cụ thể. Quân mới có thể cho nhóm chạy nối ra hoặc phản atari.',flank);
q('reading','miai','Sống/chết','Hai lựa chọn tương đương','Giả định A và B đều tạo mắt thứ hai; đối phương chỉ chiếm được một điểm, không có atari hay cách phá đồng thời. Nhóm có cần lập tức tự chiếm một điểm không?',['Không bắt buộc: có thể đáp ở điểm còn lại','Có, luôn phải tự chiếm cả hai'],0,'Theo giả định, A và B là miai: nếu mất một, đáp ở điểm kia. Trong ván thật phải kiểm tra điều kiện bị loại trừ.');
q('reading','false-eye','Sống/chết','Đọc mắt giả','Một điểm trống trông như mắt, nhưng quân bao quanh nó thuộc nhiều nhóm và có thể bị atari ép lấp điểm đó. Cách kiểm tra đúng là gì?',['Đếm nó như mắt thật ngay','Đọc liên kết và các nước bắt ép nhóm bao quanh'],1,'Mắt thật phụ thuộc hình và liên kết của các quân bao quanh. Chỉ một điểm trống bị bao chưa đủ.');
q('reading','weak-group','Toàn bàn','Ưu tiên nhóm yếu','Một nhóm của bạn đang bị cắt, chưa có mắt và bị địch bao quanh; nhóm khác đã sống chắc. Khi giá trị các vùng tương đương, nên kiểm tra gì trước?',['Phòng thủ hoặc đường chạy cho nhóm yếu','Gia cố nhóm đã sống chắc'],0,'Nhóm yếu có thể mất quân, mất đất và trao địch tiên thủ. Tuy nhiên có thể hy sinh nếu đổi lại đủ lợi ích.',middle);
q('reading','direction','Toàn bàn','Tránh đuổi về phía yếu','Giả định có hai hướng tấn công tương đương về đất. A đuổi địch vào nhóm yếu của bạn; B đuổi về nhóm mạnh của bạn. Hướng nào ít rủi ro hơn?',['A','B'],1,'B tận dụng quân mạnh làm hậu thuẫn. A có thể khiến nhóm yếu của bạn chịu phản công. Đây là lựa chọn theo giả định, không là nước tối ưu được AI xác nhận.',flank);
q('reading','score-estimate','Đếm điểm','Không quên komi','Đếm diện tích: đen 147, trắng 140, trung lập 74 trên bàn 19×19. Komi 6,5 cho trắng. Ai hơn?',['Đen 0,5','Đen 7','Trắng 0,5'],0,'Trắng = 146,5; đen = 147. Đen hơn 0,5. 147 + 140 + 74 = 361.');
q('reading','tenuki','Toàn bàn','Đi nơi khác có mất gì?','Bạn muốn bỏ qua nước địch để đi điểm lớn. Câu hỏi đầu tiên nên là gì?',['Nếu bỏ qua, địch thực sự đe dọa mất bao nhiêu và có giết nhóm không?','Nước địch có tên joseki không?'],0,'Đánh giá hậu quả của việc không đáp. Tên mẫu không thay thế đọc chiến thuật và so sánh toàn bàn.',opening);

q('strategy','sente','Quan tử','Tiên thủ là quan hệ đáp trả','Nước quan tử lấy 3 điểm. Đối phương có thể bỏ qua mà không chịu thiệt hại đáng kể. Có thể gọi nó là tiên thủ chỉ vì bạn đi trước không?',['Có','Không'],1,'Tiên thủ liên quan việc đối phương cần đáp để tránh tổn thất đủ lớn. Đi trước không tự tạo sente.');
q('strategy','gote-order','Quan tử','Thứ tự hai điểm hậu thủ','Giả định A và B là các vùng độc lập, đều hậu thủ, không nước tiếp và cùng cách định giá: A có giá trị 8, B có giá trị 5. Chọn gì trước?',['A','B'],0,'Với các giả định này, chọn vùng hậu thủ lớn hơn trước. Quy tắc không áp dụng nguyên xi cho sente hay reverse sente.');
q('strategy','swing','Quan tử','Độ chênh giữa hai kết quả','Ở một vùng: đen đi trước thì chênh lệch đen−trắng là +4; trắng đi trước thì là −4. Độ chênh giữa hai kết quả là bao nhiêu?',['4','8','16'],1,'(+4) − (−4) = 8. Đây là swing giữa hai kết quả, chưa tự động là giá trị nước đi để so với mọi loại quan tử.');
q('strategy','ko-size','Ko','Đe dọa chưa đủ lớn','Ko có giá trị 12 điểm theo cùng thước đo. Đe dọa của bạn nếu bị bỏ qua chỉ tạo thêm 3 điểm, không ảnh hưởng sống/chết hay tiên thủ. Đối phương có bắt buộc đáp không?',['Có, cứ là đe dọa ko phải đáp','Không; họ có thể nhường 3 để giữ ko'],1,'Đối phương có thể chấp nhận thiệt hại nhỏ để thắng ko lớn. Phải tính cả chi phí tạo và đáp đe dọa.');
q('strategy','ko-local','Ko','Kết quả địa phương và toàn bàn','Một bài sống/chết chỉ cho nhóm có thể sống bằng ko. Có được kết luận nhóm sống chắc trong ván thật không?',['Có','Không: còn phụ thuộc đe dọa ko và giá trị toàn bàn'],1,'Ko là kết quả có điều kiện. Khả năng thắng ko không nằm trọn trong sơ đồ địa phương.');
q('strategy','invasion','Toàn bàn','Xâm nhập hay giảm đất?','Địch có khung rộng nhưng chưa kín. Giả định xâm nhập sâu tạo nhóm không đường chạy; giảm đất từ ngoài giữ nhóm bạn nối an toàn. Bạn ưu tiên kiểm tra phương án nào để hạn chế rủi ro?',['Giảm đất từ ngoài','Luôn xâm nhập sâu'],0,'Giảm đất giữ liên lạc có thể tránh tạo nhóm yếu. Cần so phần đất nhường với lợi ích và các biến thực tế.',opening);
q('strategy','attack-profit','Toàn bàn','Lợi ích của tấn công','Địch chạy thoát nhưng bạn xây được đất vững và gia cố nhóm yếu mà không trả giá lớn. Có nhất thiết coi tấn công thất bại vì chưa bắt được quân không?',['Có','Không'],1,'Tấn công có thể nhằm tạo đất, ảnh hưởng hoặc gia cố nhóm. Bắt quân chỉ là một loại lợi ích.',middle);
q('strategy','sacrifice','Chiến thuật','Đừng cứu mọi quân','Cứu 2 quân nhỏ mất 4 nước hậu thủ và làm nhóm lớn của bạn yếu đi; bỏ 2 quân cho bạn cơ hội cứu nhóm lớn. Nên đánh giá thế nào?',['Cứu mọi quân đã đặt','So lợi ích toàn bàn và giá trị nhóm lớn'],1,'Quân đã đặt là chi phí đã bỏ ra. Chọn theo hậu quả tiếp theo, không theo số quân muốn giữ bằng mọi giá.');
q('strategy','joseki','Toàn bàn','Mẫu đúng, hướng sai','Một biến góc cân bằng tại chỗ nhưng ảnh hưởng nó tạo ra hướng vào quân địch mạnh, còn phía cần hỗ trợ của bạn bị bỏ trống. Bạn nên làm gì?',['Theo nguyên mẫu vì là joseki','So các biến góc theo hướng chơi toàn bàn'],1,'Cân bằng địa phương không đảm bảo lựa chọn toàn bàn tốt. Quân sẵn có và nhóm yếu quyết định hướng phù hợp.',flank);
q('strategy','aji','Chiến thuật','Giữ khả năng về sau','Một quân cắt hiện chưa bắt được. Nó vẫn có thể tạo đe dọa ko hoặc phối hợp với quân ở xa. Trước khi tự xóa mọi khả năng đó, cần cân nhắc gì?',['Aji: các biến và đe dọa còn lại','Chỉ kết quả bắt ngay'],0,'Aji là khả năng còn tiềm ẩn trong thế cờ. Chỉ giữ aji khi lợi ích lớn hơn nguy cơ và chi phí.');

q('dan','verify-reading','Đọc biến','Đối phương không đáp theo ý mình','Bạn tìm được một chuỗi thắng nếu địch đáp A, nhưng chưa kiểm tra B và nước bỏ lượt. Có đủ để tuyên bố bắt cưỡng bức không?',['Đủ','Chưa đủ'],1,'Một biến thắng không chứng minh thắng cưỡng bức. Cần xét các đáp hợp lệ có thể thay đổi kết quả.');
q('dan','capture-deadline','Đọc biến','Giới hạn của bài đọc','Bộ đọc xác nhận bắt nhóm mục tiêu trong tối đa 11 lượt trên bàn 5×5 dưới positional superko. Điều nào được chứng minh?',['Sức chơi 1 dan của người giải','Khả năng bắt cưỡng bức của thế cụ thể trong giới hạn đã nêu'],1,'Chứng minh địa phương có giới hạn không suy ra rank, chất lượng khai cuộc hay quyết định toàn bàn.');
q('dan','ko-count','Ko','Ngân sách đe dọa','Hai bên tranh ko có cùng giá trị. Bạn có 1 đe dọa đủ lớn đã xác nhận; địch có 3, các điều kiện khác ngang nhau. Cách chuẩn bị hợp lý là gì?',['Tìm thêm đe dọa hoặc phương án tránh ko, tính lại toàn bàn','Cứ bắt lại vì bạn khởi động ko'],0,'Thiếu đe dọa có thể khiến bạn phải nhường ko. Số lượng chỉ có nghĩa sau khi kiểm tra giá trị và thứ tự dùng.');
q('dan','reverse-sente','Quan tử','Đừng so bằng con số trần','A là hậu thủ, B ngăn một nước tiên thủ của địch. Hai giá trị ghi trong sổ cùng là 6 nhưng dùng cách định giá khác nhau. Có thể chọn tùy ý vì cùng 6 không?',['Có','Không, cần đổi về cùng cách so và đọc quyền chủ động'],1,'Hậu thủ, tiên thủ và reverse sente không được so bằng các con số dùng định nghĩa khác nhau.');
q('dan','threat-cost','Ko','Chi phí tự tạo đe dọa','Đe dọa ko làm địch mất 10 nếu bỏ qua, nhưng khi họ đáp, chính bạn phải bỏ 8 điểm vốn giữ được. Có thể coi nó là đe dọa miễn phí không?',['Có','Không'],1,'Phải tính chi phí dùng đe dọa, không chỉ thiệt hại nếu đối phương bỏ qua.');
q('dan','end-score','Đếm điểm','Ván sát điểm','Bàn 19×19, không trung lập hay quân chết: đen 190 diện tích, trắng 171. Komi 6,5. Kết quả?',['Đen hơn 12,5','Đen hơn 19','Trắng hơn 6,5'],0,'Trắng = 177,5. Đen hơn 12,5. Tổng diện tích trước komi là 361.');
q('dan','seki-area','Đếm điểm','Điểm trong sống chung','Theo cách đếm diện tích, có hai quân sống của đen trong seki và ba điểm khí chung giáp hai màu. Phần này cộng gì cho đen?',['2 điểm quân; 0 điểm khí chung','5 điểm','0 vì seki không tính quân'],0,'Quân sống vẫn tính trong diện tích. Khí chung giáp hai màu không thuộc vùng đất riêng. Đừng trộn với cách đếm Nhật.');
q('dan','time-management','Thực chiến','Thiếu thời gian đọc','Trong byo-yomi, một nhóm lớn bị atari. Bạn chưa đọc xong cả cuộc tấn công và còn một nước nối an toàn đã xác nhận. Chọn theo tiêu chí nào?',['Đọc đe dọa trực tiếp, ưu tiên kết quả đã xác nhận nếu không đủ thời gian','Chọn nước đẹp nhất dù chưa kiểm tra'],0,'Quản lý thời gian là một phần thực chiến. Giảm biến chưa xác nhận khi hậu quả mất nhóm lớn.');
q('dan','review-method','Thực chiến','Xem lại một ván thua','Bạn muốn biến một sai lầm thành bài tập. Dữ liệu hữu ích nhất là gì?',['Thế trước sai lầm, các nước ứng viên, đáp phản bác và kết quả đọc','Chỉ kết quả thua bao nhiêu điểm'],0,'Lưu thế và quyết định giúp tái giải mà không nhìn đáp án. Kết quả ván riêng lẻ không giải thích nguyên nhân.');
q('dan','rank-proof','Thực chiến','Khi nào xác nhận mục tiêu?','Bạn giải hết ngân hàng bài ở app. Bằng chứng nào cần bổ sung để đánh giá sức chơi 1 dan?',['Số bài đã bấm hoàn thành','Kết quả thực chiến với đối thủ có hạng trong cùng hệ rating'],1,'Rank cần hiệu chuẩn theo kết quả chơi thực. Các nền tảng và hệ rating có thể khác nhau; app không tự cấp đẳng.');
export {questions};
export function stageForDepth(depth) { return depth === 1 ? 'foundation' : depth === 3 ? 'tactics' : depth === 5 ? 'reading' : depth === 7 ? 'strategy' : 'dan'; }
export function buildBank(readingBank) {
  return [...readingBank.map((p,i)=>({
    ...p,id:p.id,kind:'reading',stage:p.goal==='eyes'?(p.depth===1?'tactics':p.depth===3?'reading':p.depth===5?'strategy':'dan'):stageForDepth(p.depth),topic:p.shape==='tactical'?'Đọc biến':'Sống/chết',
    title:p.goal==='eyes'?`Tạo hai mắt · ${i+1}`:p.shape==='tactical'?`Đọc bắt quân · ${i+1}`:`Phá không gian mắt · ${i+1}`,
    prompt:p.goal==='eyes'?`Đen đi trước. Tạo hai mắt thật riêng cho nhóm đen có dấu tam giác trong tối đa ${Math.ceil(p.depth/2)} lượt đen (${p.depth} lượt cả hai bên). Trắng được đáp ở mọi điểm hợp lệ hoặc bỏ lượt.`:`Đen đi trước. Bắt nhóm trắng có dấu tam giác trong tối đa ${Math.ceil(p.depth/2)} lượt đen (${p.depth} lượt cả hai bên). Trắng có thể đáp ở mọi điểm hợp lệ hoặc bỏ lượt.`,
    explanation:p.goal==='eyes'?'Mục tiêu là hai điểm trống riêng, mỗi điểm chỉ giáp quân của cùng nhóm đen được đánh dấu. Đây là điều kiện đủ để nhóm sống dưới luật cấm tự sát. Bộ đọc xét tất cả đáp hợp lệ trong giới hạn lượt; không đánh giá sức chơi toàn bàn.':'Mọi nước đặt quân hợp lệ của hai bên và bỏ lượt của trắng được xét trên toàn bộ bàn bài tập, dưới positional superko. Đây là bài bắt có thời hạn; không phân tích ko toàn bàn 19×19 và không hiệu chuẩn rank.'
  })),...questions];
}
