export const stages = [
  {id:'foundation',name:'30–20 kyu',focus:'Khí, bắt quân, luật và đếm diện tích',practice:'Chơi 3 ván 9×9. Sau mỗi ván, ghi lại một nhóm mất quân vì thiếu khí.'},
  {id:'tactics',name:'20–10 kyu',focus:'Đọc hai nước đen, nối/cắt và hình cờ',practice:'Chơi 3 ván 13×13 hoặc 19×19. Xem lại các điểm cắt và nhóm chỉ còn một khí.'},
  {id:'reading',name:'10–5 kyu',focus:'Đọc nhiều đáp trả, hướng chơi và sống/chết',practice:'Chơi 5 ván 19×19 với đối thủ có hạng. Chọn hai quyết định sai mỗi ván để tự đọc lại.'},
  {id:'strategy',name:'5–1 kyu',focus:'Tấn công, ko, quan tử và lựa chọn toàn bàn',practice:'Chơi 5 ván 19×19. Nhờ người mạnh hơn hoặc công cụ phân tích xem lại nhóm yếu và các nước quan tử lớn.'},
  {id:'dan',name:'Mục tiêu 1 dan',focus:'Đọc sâu và kiểm tra quyết định dưới áp lực',practice:'Duy trì thực chiến 19×19 với đối thủ có rating ổn định. Theo dõi kết quả và nhờ người mạnh hơn kiểm tra các ván. Hoàn thành bài tập không tự xác nhận 1 dan.'},
  {id:'dan2',name:'Mục tiêu 2 dan',focus:'Định lượng quan tử, đọc phản bác và kế hoạch toàn bàn',practice:'Xem lại 5 ván 19×19 của bạn trong phòng SGF. Trước khi xem phân tích, ghi hai ứng viên và nước phản bác mạnh nhất. Đối chiếu với người mạnh hơn; ghi lỗi lặp lại.'},
  {id:'dan3',name:'Mục tiêu 3 dan nghiệp dư',focus:'Ko có điều kiện, quyết định sát điểm và tự kiểm tra biến',practice:'Chơi với đối thủ có rating ổn định trong cùng hệ. Xem lại khai cuộc, trung bàn và quan tử; nhờ người mạnh hơn kiểm tra các kết luận. Theo dõi rating thực chiến, không suy đẳng từ điểm bài tập.'}
];
const letters='ABCDEFGHJKLMNOPQRST';
function diagram(size, black=[], white=[]) {
  const point = coordinate => (size-Number(coordinate.slice(1)))*size+letters.indexOf(coordinate[0]);
  return {size,setup:[...black.map(c=>[point(c),1]),...white.map(c=>[point(c),2])]};
}
const opening=diagram(19,['D4','Q16'],['Q4','D16']);
const flank=diagram(19,['D4','F4','Q16'],['D16','Q4','Q10']);
const middle=diagram(19,['D4','F4','F6','D16'],['G4','G5','Q4','Q16']);
const questions=[];
function q(stage,id,topic,title,prompt,choices,answer,explanation,position={size:0,setup:[]}) {
  questions.push({id:`q-${id}`,stage,topic,title,prompt,choices,answer,explanation,kind:'quiz',...position});
}
q('foundation','diagonal','Khí','Nối chéo có chia sẻ khí?','Hai quân cùng màu chỉ chạm chéo, không có quân nối ngang/dọc. Chúng là một nhóm chưa?',['Đã là một nhóm','Vẫn là hai nhóm'],1,'Chỉ kết nối ngang và dọc tạo thành nhóm. Liên kết chéo có thể bị cắt.',diagram(5,['B3','C2']));
q('foundation','corner-liberties','Khí','Khí ở góc','Một quân ở A5 trên bàn 5×5 trống có bao nhiêu khí?',['1','2','3','4'],1,'Chỉ có B5 và A4; biên bàn không phải giao điểm trống.',diagram(5,['A5']));
q('foundation','edge-liberties','Khí','Khí ở biên','Một quân ở C5 trên bàn trống có bao nhiêu khí?',['2','3','4'],1,'B5, D5, C4: 3 khí. Không có giao điểm phía ngoài bàn.',diagram(5,['C5']));
q('foundation','capture-order','Luật','Thứ tự khi đặt quân','Một nước đen lấp hết khí của nhóm trắng, đồng thời điểm đen đặt ban đầu chưa có khí. Phải kiểm tra gì trước?',['Bắt nhóm trắng hết khí, rồi kiểm tra khí đen','Cấm nước đi ngay vì ban đầu chưa có khí'],0,'Bắt các nhóm đối phương hết khí trước. Nếu sau khi nhấc trắng, nhóm đen có khí, nước đi có thể hợp lệ; vẫn phải kiểm tra lặp thế.');
q('foundation','area-captures','Đếm điểm','Quân đã bắt có cộng riêng?','Trong cách đếm diện tích của app, điểm bằng quân trên bàn cộng đất. Có cộng thêm số quân đã bắt vào điểm này không?',['Có','Không'],1,'Không cộng riêng tù binh trong cách đếm diện tích. Đừng trộn cách đếm đất với cách đếm diện tích.');
q('foundation','area-total','Đếm điểm','Một phép đếm nhỏ','Cuối ván: đen có 12 quân sống và 9 điểm đất, trắng có 10 quân sống và 8 điểm đất. Komi 6,5 cho trắng. Ai hơn?',['Đen hơn 3','Trắng hơn 3,5','Hòa'],1,'Đen = 12 + 9 = 21. Trắng = 10 + 8 + 6,5 = 24,5. Trắng hơn 3,5.');
q('foundation','neutral','Đếm điểm','Vùng giáp cả hai màu','Một vùng trống liên thông chỉ giáp cả quân đen lẫn quân trắng. Với cách đếm diện tích hiện tại, vùng này thuộc ai?',['Đen','Trắng','Không bên nào'],2,'Vùng giáp hai màu là vùng trung lập trong phép đếm vùng của app. Điều này không tự giải quyết quân chết.');
q('foundation','pass','Luật','Kết thúc ván luyện','Hai bên bỏ lượt liên tiếp. Có thể kết luận bộ đếm hiện tại đã phân xử đúng mọi quân chết chưa?',['Có, bỏ lượt tự xác nhận mọi nhóm sống','Chưa, cần xử lý quân chết hoặc chơi tiếp'],1,'Hai lượt bỏ kết thúc ván, nhưng thuật toán hiện tại không tự phân xử sống/chết. Chơi tiếp để bắt quân chết hoặc nhờ phân xử.');

q('tactics','shared','Khí','Khí chung chỉ đếm một lần','Hai quân đen B3 và C3 đứng cạnh nhau trên bàn trống. Cả nhóm có bao nhiêu khí?',['4','5','6','8'],2,'A3, B4, B2, D3, C4, C2: 6 điểm khác nhau.',diagram(5,['B3','C3']));
q('tactics','self-atari','Hình cờ','Nhận diện tự atari','Sau một nước hợp lệ, nhóm vừa đi chỉ còn một khí. Nếu không có lý do hy sinh hay bắt quân, cần kiểm tra điều gì?',['Nguy cơ đối phương bắt ở khí cuối','Chỉ số quân vừa nối được'],0,'Hợp lệ không đồng nghĩa an toàn. Tự atari cần được đọc đến nước bắt của đối phương.');
q('tactics','two-eyes','Sống/chết','Một khoảng trống lớn','Một nhóm bao quanh hai điểm trống liền nhau. Có chắc đã có hai mắt riêng không?',['Có, hai điểm là hai mắt','Không, đó có thể chỉ là một không gian mắt'],1,'Hai mắt phải là hai vùng riêng có khả năng bảo vệ nhóm. Số điểm trống không bằng số mắt.');
q('tactics','double-atari','Chiến thuật','Atari kép chưa phải kết luận','Một nước đưa hai nhóm địch vào atari. Để kết luận sẽ bắt được ít nhất một nhóm, còn phải kiểm tra gì?',['Địch có nước bắt, nối hoặc cứu đồng thời không','Không cần đọc thêm'],0,'Atari kép tạo hai đe dọa, nhưng phản công hoặc nối nhóm có thể hóa giải cả hai.');
q('tactics','ladder','Đọc biến','Trước khi đuổi thang','Một chuỗi atari dự kiến chạy chéo qua bàn. Điều gì phải kiểm tra ngoài vài nước đầu?',['Các quân nằm trên đường thang và điểm kết thúc','Chỉ khí của quân đầu tiên'],0,'Quân phá thang ở xa có thể giúp nhóm bị đuổi nối ra ngoài. Đọc tới điểm kết thúc hoặc tới kết nối an toàn.',opening);
q('tactics','net','Đọc biến','Lưới và atari','Có thể dùng một nước không atari để chặn mọi đường thoát của nhóm địch không?',['Không, phải atari ở mọi nước','Có, đó là ý tưởng của lưới'],1,'Lưới có thể bắt bằng chặn lối thoát, thay vì ép theo một chuỗi atari. Phải kiểm tra các đường xuyên lưới.');
q('tactics','snapback','Chiến thuật','Bắt lại sau hy sinh','Đen hy sinh một quân, trắng bắt, rồi đen bắt ngược ba quân trắng. Thế bàn mới khác mọi thế trước. Có bị cấm chỉ vì bắt lại ngay không?',['Có, mọi bắt lại ngay là ko','Không; vẫn kiểm tra tự sát và lịch sử thế bàn'],1,'Bắt lại ngay không tự động là ko. Snapback lấy nhóm lớn hơn và có thể tạo một thế hoàn toàn khác.');
q('tactics','corner-efficiency','Toàn bàn','Đất và biên bàn','Trên bàn 19×19 trống, nếu mục tiêu là bao vùng nhỏ bằng ít đường rào nhất, góc có lợi thế gì?',['Hai cạnh bàn làm sẵn một phần ranh giới','Góc được nhân đôi điểm'],0,'Hai cạnh giúp giảm số phía phải bao. Đây là lý do hình học, không phải quy tắc mọi nước khai cuộc đều ở góc.',{size:19,setup:[]});

q('reading','race','Đọc biến','Đua bắt đơn giản','Giả định hai nhóm không mắt, không khí chung, không nối/ko/throw-in; đen có 3 khí ngoài, trắng có 2. Hai bên chỉ lần lượt lấp khí đối phương, đen đi trước. Ai bắt trước?',['Đen','Trắng','Chắc chắn seki'],0,'Đen lấp 1, trắng lấp 1, đen lấp khí cuối của trắng và bắt. Các giả định đã loại bỏ những trường hợp làm công thức đếm khí sai.');
q('reading','shared-race','Đọc biến','Khi không dùng phép trừ khí','Hai nhóm có khí chung và một bên có mắt. Có nên chỉ lấy số khí ngoài trừ nhau để kết luận không?',['Có, luôn đúng','Không, phải đọc thứ tự lấp khí và mắt'],1,'Khí chung, mắt, nối, ko và nước hy sinh thay đổi thứ tự bắt. Phép đếm đơn giản cần đúng điều kiện áp dụng.');
q('reading','ladder-breaker','Đọc biến','Quân phá thang thay đổi','Biến thang lúc đầu bắt được. Đối phương vừa đặt thêm một quân đúng đường chạy của thang. Lần tới bạn có thể dùng nguyên kết luận cũ không?',['Có, thang đã được chứng minh','Không, phải đọc lại tới quân mới'],1,'Kết quả đọc thuộc một thế bàn cụ thể. Quân mới có thể cho nhóm chạy nối ra hoặc phản atari.',flank);
q('reading','miai','Sống/chết','Hai lựa chọn tương đương','Giả định A và B đều tạo mắt thứ hai; đối phương chỉ chiếm được một điểm, không có atari hay cách phá đồng thời. Nhóm có cần lập tức tự chiếm một điểm không?',['Không bắt buộc: có thể đáp ở điểm còn lại','Có, luôn phải tự chiếm cả hai'],0,'Theo giả định, A và B là miai: nếu mất một, đáp ở điểm kia. Trong ván thật phải kiểm tra điều kiện bị loại trừ.');
q('reading','false-eye','Sống/chết','Đọc mắt giả','Một điểm trống trông như mắt, nhưng quân bao quanh nó thuộc nhiều nhóm và có thể bị atari ép lấp điểm đó. Cách kiểm tra đúng là gì?',['Đếm nó như mắt thật ngay','Đọc liên kết và các nước bắt ép nhóm bao quanh'],1,'Mắt thật phụ thuộc hình và liên kết của các quân bao quanh. Chỉ một điểm trống bị bao chưa đủ.');
q('reading','weak-group','Toàn bàn','Ưu tiên nhóm yếu','Một nhóm của bạn đang bị cắt, chưa có mắt và bị địch bao quanh; nhóm khác đã sống chắc. Khi giá trị các vùng tương đương, nên kiểm tra gì trước?',['Phòng thủ hoặc đường chạy cho nhóm yếu','Gia cố nhóm đã sống chắc'],0,'Nhóm yếu có thể mất quân, mất đất và trao địch tiên thủ. Tuy nhiên có thể hy sinh nếu đổi lại đủ lợi ích.',middle);
q('reading','direction','Toàn bàn','Tránh đuổi về phía yếu','Giả định có hai hướng tấn công tương đương về đất. A đuổi địch vào nhóm yếu của bạn; B đuổi về nhóm mạnh của bạn. Hướng nào ít rủi ro hơn?',['A','B'],1,'B tận dụng quân mạnh làm hậu thuẫn. A có thể khiến nhóm yếu của bạn chịu phản công. Đây là lựa chọn theo giả định, không là nước tối ưu được AI xác nhận.',flank);
q('reading','score-estimate','Đếm điểm','Không quên komi','Đếm diện tích: đen 147, trắng 140, trung lập 74 trên bàn 19×19. Komi 6,5 cho trắng. Ai hơn?',['Đen 0,5','Đen 7','Trắng 0,5'],0,'Trắng = 146,5; đen = 147. Đen hơn 0,5. 147 + 140 + 74 = 361.');
q('reading','tenuki','Toàn bàn','Đi nơi khác có mất gì?','Bạn muốn bỏ qua nước địch để đi điểm lớn. Câu hỏi đầu tiên nên là gì?',['Nếu bỏ qua, địch thực sự đe dọa mất bao nhiêu và có giết nhóm không?','Nước địch có tên joseki không?'],0,'Đánh giá hậu quả của việc không đáp. Tên mẫu không thay thế đọc chiến thuật và so sánh toàn bàn.',opening);

q('strategy','sente','Quan tử','Tiên thủ là quan hệ đáp trả','Nước quan tử lấy 3 điểm. Đối phương có thể bỏ qua mà không chịu thiệt hại đáng kể. Có thể gọi nó là tiên thủ chỉ vì bạn đi trước không?',['Có','Không'],1,'Tiên thủ liên quan việc đối phương cần đáp để tránh tổn thất đủ lớn. Đi trước không tự tạo sente.');
q('strategy','gote-order','Quan tử','Thứ tự hai điểm hậu thủ','Giả định A và B là các vùng độc lập, đều hậu thủ, không nước tiếp và cùng cách định giá: A có giá trị 8, B có giá trị 5. Chọn gì trước?',['A','B'],0,'Với các giả định này, chọn vùng hậu thủ lớn hơn trước. Quy tắc không áp dụng nguyên xi cho sente hay reverse sente.');
q('strategy','swing','Quan tử','Độ chênh giữa hai kết quả','Ở một vùng: đen đi trước thì chênh lệch đen−trắng là +4; trắng đi trước thì là −4. Độ chênh giữa hai kết quả là bao nhiêu?',['4','8','16'],1,'(+4) − (−4) = 8. Đây là swing giữa hai kết quả, chưa tự động là giá trị nước đi để so với mọi loại quan tử.');
q('strategy','ko-size','Ko','Đe dọa chưa đủ lớn','Ko có giá trị 12 điểm theo cùng thước đo. Đe dọa của bạn nếu bị bỏ qua chỉ tạo thêm 3 điểm, không ảnh hưởng sống/chết hay tiên thủ. Đối phương có bắt buộc đáp không?',['Có, cứ là đe dọa ko phải đáp','Không; họ có thể nhường 3 để giữ ko'],1,'Đối phương có thể chấp nhận thiệt hại nhỏ để thắng ko lớn. Phải tính cả chi phí tạo và đáp đe dọa.');
q('strategy','ko-local','Ko','Kết quả địa phương và toàn bàn','Một bài sống/chết chỉ cho nhóm có thể sống bằng ko. Có được kết luận nhóm sống chắc trong ván thật không?',['Có','Không: còn phụ thuộc đe dọa ko và giá trị toàn bàn'],1,'Ko là kết quả có điều kiện. Khả năng thắng ko không nằm trọn trong sơ đồ địa phương.');
q('strategy','invasion','Toàn bàn','Xâm nhập hay giảm đất?','Địch có khung rộng nhưng chưa kín. Giả định xâm nhập sâu tạo nhóm không đường chạy; giảm đất từ ngoài giữ nhóm bạn nối an toàn. Bạn ưu tiên kiểm tra phương án nào để hạn chế rủi ro?',['Giảm đất từ ngoài','Luôn xâm nhập sâu'],0,'Giảm đất giữ liên lạc có thể tránh tạo nhóm yếu. Cần so phần đất nhường với lợi ích và các biến thực tế.',opening);
q('strategy','attack-profit','Toàn bàn','Lợi ích của tấn công','Địch chạy thoát nhưng bạn xây được đất vững và gia cố nhóm yếu mà không trả giá lớn. Có nhất thiết coi tấn công thất bại vì chưa bắt được quân không?',['Có','Không'],1,'Tấn công có thể nhằm tạo đất, ảnh hưởng hoặc gia cố nhóm. Bắt quân chỉ là một loại lợi ích.',middle);
q('strategy','sacrifice','Chiến thuật','Đừng cứu mọi quân','Cứu 2 quân nhỏ mất 4 nước hậu thủ và làm nhóm lớn của bạn yếu đi; bỏ 2 quân cho bạn cơ hội cứu nhóm lớn. Nên đánh giá thế nào?',['Cứu mọi quân đã đặt','So lợi ích toàn bàn và giá trị nhóm lớn'],1,'Quân đã đặt là chi phí đã bỏ ra. Chọn theo hậu quả tiếp theo, không theo số quân muốn giữ bằng mọi giá.');
q('strategy','joseki','Toàn bàn','Mẫu đúng, hướng sai','Một biến góc cân bằng tại chỗ nhưng ảnh hưởng nó tạo ra hướng vào quân địch mạnh, còn phía cần hỗ trợ của bạn bị bỏ trống. Bạn nên làm gì?',['Theo nguyên mẫu vì là joseki','So các biến góc theo hướng chơi toàn bàn'],1,'Cân bằng địa phương không đảm bảo lựa chọn toàn bàn tốt. Quân sẵn có và nhóm yếu quyết định hướng phù hợp.',flank);
q('strategy','aji','Chiến thuật','Giữ khả năng về sau','Một quân cắt hiện chưa bắt được. Nó vẫn có thể tạo đe dọa ko hoặc phối hợp với quân ở xa. Trước khi tự xóa mọi khả năng đó, cần cân nhắc gì?',['Aji: các biến và đe dọa còn lại','Chỉ kết quả bắt ngay'],0,'Aji là khả năng còn tiềm ẩn trong thế cờ. Chỉ giữ aji khi lợi ích lớn hơn nguy cơ và chi phí.');

q('dan','verify-reading','Đọc biến','Đối phương không đáp theo ý mình','Bạn tìm được một chuỗi thắng nếu địch đáp A, nhưng chưa kiểm tra B và nước bỏ lượt. Có đủ để tuyên bố bắt cưỡng bức không?',['Đủ','Chưa đủ'],1,'Một biến thắng không chứng minh thắng cưỡng bức. Cần xét các đáp hợp lệ có thể thay đổi kết quả.');
q('dan','capture-deadline','Đọc biến','Giới hạn của bài đọc','Bộ đọc xác nhận bắt nhóm mục tiêu trong tối đa 11 lượt trên bàn 5×5 dưới positional superko. Điều nào được chứng minh?',['Sức chơi 1 dan của người giải','Khả năng bắt cưỡng bức của thế cụ thể trong giới hạn đã nêu'],1,'Chứng minh địa phương có giới hạn không suy ra rank, chất lượng khai cuộc hay quyết định toàn bàn.');
q('dan','ko-count','Ko','Ngân sách đe dọa','Hai bên tranh ko có cùng giá trị. Bạn có 1 đe dọa đủ lớn đã xác nhận; địch có 3, các điều kiện khác ngang nhau. Cách chuẩn bị hợp lý là gì?',['Tìm thêm đe dọa hoặc phương án tránh ko, tính lại toàn bàn','Cứ bắt lại vì bạn khởi động ko'],0,'Thiếu đe dọa có thể khiến bạn phải nhường ko. Số lượng chỉ có nghĩa sau khi kiểm tra giá trị và thứ tự dùng.');
q('dan','reverse-sente','Quan tử','Đừng so bằng con số trần','A là hậu thủ, B ngăn một nước tiên thủ của địch. Hai giá trị ghi trong sổ cùng là 6 nhưng dùng cách định giá khác nhau. Có thể chọn tùy ý vì cùng 6 không?',['Có','Không, cần đổi về cùng cách so và đọc quyền chủ động'],1,'Hậu thủ, tiên thủ và reverse sente không được so bằng các con số dùng định nghĩa khác nhau.');
q('dan','threat-cost','Ko','Chi phí tự tạo đe dọa','Đe dọa ko làm địch mất 10 nếu bỏ qua, nhưng khi họ đáp, chính bạn phải bỏ 8 điểm vốn giữ được. Có thể coi nó là đe dọa miễn phí không?',['Có','Không'],1,'Phải tính chi phí dùng đe dọa, không chỉ thiệt hại nếu đối phương bỏ qua.');
q('dan','end-score','Đếm điểm','Ván sát điểm','Bàn 19×19, không trung lập hay quân chết: đen 190 diện tích, trắng 171. Komi 6,5. Kết quả?',['Đen hơn 12,5','Đen hơn 19','Trắng hơn 6,5'],0,'Trắng = 177,5. Đen hơn 12,5. Tổng diện tích trước komi là 361.');
q('dan','seki-area','Đếm điểm','Điểm trong sống chung','Theo cách đếm diện tích, có hai quân sống của đen trong seki và ba điểm khí chung giáp hai màu. Phần này cộng gì cho đen?',['2 điểm quân; 0 điểm khí chung','5 điểm','0 vì seki không tính quân'],0,'Quân sống vẫn tính trong diện tích. Khí chung giáp hai màu không thuộc vùng đất riêng. Đừng trộn với cách đếm Nhật.');
q('dan','time-management','Thực chiến','Thiếu thời gian đọc','Trong byo-yomi, một nhóm lớn bị atari. Bạn chưa đọc xong cả cuộc tấn công và còn một nước nối an toàn đã xác nhận. Chọn theo tiêu chí nào?',['Đọc đe dọa trực tiếp, ưu tiên kết quả đã xác nhận nếu không đủ thời gian','Chọn nước đẹp nhất dù chưa kiểm tra'],0,'Quản lý thời gian là một phần thực chiến. Giảm biến chưa xác nhận khi hậu quả mất nhóm lớn.');
q('dan','review-method','Thực chiến','Xem lại một ván thua','Bạn muốn biến một sai lầm thành bài tập. Dữ liệu hữu ích nhất là gì?',['Thế trước sai lầm, các nước ứng viên, đáp phản bác và kết quả đọc','Chỉ kết quả thua bao nhiêu điểm'],0,'Lưu thế và quyết định giúp tái giải mà không nhìn đáp án. Kết quả ván riêng lẻ không giải thích nguyên nhân.');
q('dan','rank-proof','Thực chiến','Khi nào xác nhận mục tiêu?','Bạn giải hết ngân hàng bài ở app. Bằng chứng nào cần bổ sung để đánh giá sức chơi 1 dan?',['Số bài đã bấm hoàn thành','Kết quả thực chiến với đối thủ có hạng trong cùng hệ rating'],1,'Rank cần hiệu chuẩn theo kết quả chơi thực. Các nền tảng và hệ rating có thể khác nhau; app không tự cấp đẳng.');

// These finite models have explicit assumptions; no engine-derived rank labels.
for(let i=0;i<8;i++) {
  const a=6+i*2,b=3+i,margin=i*2+1;
  q('dan2',`yose-independent-${i}`,'Quan tử',`Hai vùng hậu thủ độc lập · ${i+1}`,
    `Chỉ còn hai vùng A và B, không ko, không nước tiếp. Đen đi trước, mỗi người lấy một vùng. Giá trị ở đây là mức tăng chênh lệch điểm cho bên đi: A = ${a}, B = ${b}. Đen lấy A thay vì B thì chênh lệch cuối cùng cải thiện bao nhiêu?`,
    [`${a-b} điểm`,`${2*(a-b)} điểm`,`${a+b} điểm`],1,
    `Lấy A: chênh lệch thay đổi +${a}−${b}=${a-b}. Lấy B: +${b}−${a}=${b-a}. Hai kết quả cách nhau ${2*(a-b)}. Không áp dụng con số này cho vùng tiên thủ hoặc các định nghĩa giá trị khác.`);
  const threats=1+i,opp=threats+1;
  q('dan3',`ko-budget-${i}`,'Ko',`Ngân sách ko có điều kiện · ${i+1}`,
    `Đen vừa lấy ko. Trắng có ${opp} đe dọa độc lập, Đen có ${threats}; tất cả đủ lớn và buộc đáp, mỗi lần dùng mất một đe dọa. Không phát sinh đe dọa mới; bỏ qua một đe dọa luôn tệ hơn nhường ko. Ai chốt ko?`,
    ['Đen, vì đang giữ ko','Trắng','Không thể xác định dưới các giả định này'],1,
    `Trắng dùng đe dọa rồi lấy ko; Đen dùng đe dọa rồi lấy lại. Sau ${threats} cặp, Trắng còn một đe dọa để lấy ko, Đen không còn cách lấy lại nên Trắng chốt. Trong ván thật phải kiểm tra đe dọa có độc lập, đủ lớn và gây tổn thất khi được đáp không.`);
  q('dan3',`safe-yose-${i}`,'Quan tử',`Ván sát điểm · ${i+1}`,
    `Đen đang hơn ${margin} điểm sau komi. Chỉ còn một vùng: nếu Đen đi, chênh lệch tăng ${a}; nếu Trắng đi, chênh lệch giảm ${b}. Tất cả nhóm đã sống, không ko/nước tiếp. Đen đi trước nhưng bỏ lượt. Chênh lệch cuối theo Đen−Trắng là bao nhiêu?`,
    [`${margin-b}`,`${margin+a}`,`${margin}`],0,
    `Trắng lấy vùng còn lại: ${margin}−${b}=${margin-b}. Bỏ lượt ở đây làm mất cơ hội quan tử; không được kết luận thắng chỉ từ ước lượng trước khi chơi nốt.`);
}
q('dan2','reading-refutation','Đọc biến','Biến đẹp bị phản bác','Ứng viên A thắng nếu Trắng đáp X. Đáp Y hợp lệ khiến nhóm Đen chết; ứng viên B có kết quả nhỏ hơn nhưng đã kiểm tra mọi đáp. Theo tiêu chí bảo đảm nhóm sống, chọn gì?',['A vì có biến thắng lớn','B; A chưa bảo đảm sống','A vì Y ít gặp'],1,'Một đáp phản bác đủ phủ định tính cưỡng bức của A. Xác suất đối thủ bỏ sót không thay thế chứng minh.');
q('dan2','attack-direction-2','Toàn bàn','Tấn công hai nhóm yếu','Có thể cắt hai nhóm yếu của địch nhưng chính nhóm cắt của bạn chỉ có một khí và không có biến thoát. Không có hy sinh có lợi đã đọc. Cần làm gì trước?',['Cắt ngay vì hai mục tiêu','Kiểm tra an toàn nhóm cắt và phương án giữ liên lạc'],1,'Hai nhóm yếu tạo tiềm năng tấn công kép, nhưng quân thực hiện phải chịu được phản công. Số mục tiêu không đủ để chọn nước. ',middle);
q('dan2','settled-versus-potential','Toàn bàn','Đất chắc và tiềm năng','Đen có 40 điểm chắc và khung có thể thành 30; Trắng có 55 chắc. Khung Đen chưa kiểm tra các biến xâm nhập. Có đủ để kết luận Đen hơn 15 trước komi không?',['Có: 40+30−55','Chưa; 30 là tiềm năng chưa xác nhận'],1,'Phân biệt đất chắc với khả năng phát triển. Đọc giảm đất/xâm nhập và tính komi trước khi chọn kế hoạch.',flank);
q('dan2','joseki-context-2','Toàn bàn','Đổi đất lấy ảnh hưởng','Biến A cho thêm đất góc nhưng làm nhóm biên của bạn yếu. Biến B ít đất góc hơn, nối nhóm biên và hướng ảnh hưởng vào vùng còn trống. Có đủ dữ kiện khẳng định A tốt hơn vì nhiều đất không?',['Có','Chưa; cần so chi phí cứu nhóm và giá trị ảnh hưởng'],1,'Định giá kết quả cả bàn. Không có lời giải tối ưu duy nhất khi chưa nêu thế cụ thể và biến phản bác.',flank);
q('dan2','seki-not-two-eyes','Sống/chết','Sống không nhất thiết hai mắt','Hai nhóm không có hai mắt riêng. Mỗi bên đi vào khí chung trước đều bị bắt; không có nước phá seki, ko hoặc kết nối bên ngoài. Kết luận theo giả định?',['Cả hai chết vì thiếu hai mắt','Cả hai sống chung'],1,'Seki cho phép sống mà không có hai mắt riêng. Bộ đọc tạo mắt của app chỉ kiểm tra một điều kiện đủ, không phân loại mọi dạng sống.');
q('dan2','reverse-sente-model','Quan tử','Chặn một chuỗi tiên thủ','Giả định A và B độc lập. A hậu thủ tăng chênh lệch cho người lấy 8. Ở B, Đen chặn được 2, nhưng nếu Trắng đi trước thì chuỗi tiên thủ bắt buộc đáp làm Đen mất 12, sau đó Đen lấy A. So: Đen A rồi Trắng B, với Đen B rồi Trắng A. Phương án nào tốt hơn cho Đen?',['Đen A trước','Đen B trước','Bằng nhau'],0,'A trước: +8−12=−4. B trước: +2−8=−6, nên A trước tốt hơn. Cần chọn theo hai kết quả đã nêu, không tên tiên thủ.');
q('dan2','ko-threat-dependence','Ko','Đừng đếm hai lần một đe dọa','Hai đe dọa A và B dùng chung một nhóm địch. Sau khi địch đáp A, B không còn gây thiệt hại. Có thể tính chúng thành hai đe dọa độc lập không?',['Có','Không'],1,'Đáp một đe dọa có thể xóa đe dọa khác. Ngân sách ko phải được cập nhật sau từng đáp.');
q('dan2','miai-destruction','Sống/chết','Miai bị phá đồng thời','A hoặc B đều tạo mắt thứ hai nếu còn nguyên. Địch có một nước vừa chiếm A vừa atari ép bạn nối khiến B mất tác dụng. Có thể tuyên bố nhóm sống vì miai không?',['Có','Không'],1,'Miai chỉ bảo đảm khi đối phương không thể xóa cả hai lựa chọn trong cùng chuỗi cưỡng bức.');
q('dan2','review-candidates','Thực chiến','Đối chiếu quyết định','Bạn nhập SGF và thấy nước đã chơi. Trước khi xem lời bình hoặc AI, nên ghi gì?',['Hai ứng viên, lý do và đáp phản bác dự kiến','Chỉ nhớ nước đã chơi'],0,'Ghi dự đoán trước giúp phân biệt đọc thực với nhận ra lời giải. Phòng SGF cho phép thử biến nhưng không tự xác nhận biến đúng.');
q('dan2','rating-system','Thực chiến','So hạng giữa hệ thống','Bạn có 2 dan ở hệ A, đối thủ có 2 dan ở hệ B. Chưa có dữ liệu đối chiếu hai hệ. Có thể coi hai sức chơi bằng nhau chính xác không?',['Có','Không'],1,'Hạng phụ thuộc quần thể và hệ rating. Theo dõi tiến bộ trong cùng hệ rồi mới đối chiếu bằng dữ liệu.');
q('dan3','sacrifice-compensation','Toàn bàn','Đổi nhóm lấy lợi ích chắc','Cứu nhóm nhỏ khiến Đen−Trắng thay đổi −6 sau các đáp cưỡng bức. Hy sinh nó làm Đen−Trắng thay đổi +4, đã tính quân mất, đất và mọi đáp; không còn aji hay ko. Nên chọn gì?',['Cứu vì quân đã đặt','Hy sinh: hơn phương án cứu 10 điểm'],1,'So kết quả cuối: +4−(−6)=10. Chỉ đúng khi các chi phí và nước tiếp thực sự đã được tính.',middle);
q('dan3','sente-no-answer','Quan tử','Đối phương tenuki','Bạn định giá một chuỗi là tiên thủ vì thường được đáp. Trong thế hiện tại, địch có thể tenuki sang nước cứu nhóm lớn giá trị hơn, và bạn không có tiếp diễn đáng kể. Cần cập nhật gì?',['Giữ nhãn tiên thủ của mẫu','Tính lại giá trị và quyền chủ động trong thế hiện tại'],1,'Sente là quan hệ giữa đe dọa và các lựa chọn thực tế. Thói quen đáp không là bằng chứng bắt buộc đáp.');
q('dan3','ko-exit','Ko','Thoát ko khi đang dẫn','Theo cùng thước đo cuối ván: nhường ko nhưng chơi điểm lớn cho bạn thắng chắc 2; tiếp tục ko có thể thắng 12 hoặc thua 8 tùy đe dọa chưa kiểm tra. Nếu mục tiêu là bảo đảm thắng theo các dữ kiện đã xác nhận, chọn gì?',['Phương án thắng chắc 2','Tiếp tục vì có thể thắng 12'],0,'Chọn kết quả đã xác nhận khi tiêu chí là bảo đảm thắng. Không suy ra quy tắc luôn tránh ko khi dẫn điểm.');
q('dan3','aji-keshi','Chiến thuật','Trao đổi xóa aji','Một trao đổi buộc địch nối, làm mất điểm cắt bạn định khai thác sau. Nó không tạo đất, an toàn hay đe dọa có lợi đã xác nhận. Có nên tự coi là lợi vì được đáp không?',['Có, buộc đáp luôn tốt','Không, có thể là aji-keshi'],1,'Một nước được đáp vẫn có thể giúp địch sửa điểm yếu. So kết quả trước/sau trao đổi và cơ hội bị mất.');
q('dan3','reading-horizon','Đọc biến','Biến vượt giới hạn bộ đọc','Công cụ thử biến cho phép đặt quân hợp lệ nhưng chưa tính mọi đáp. Bạn đặt một chuỗi 15 nước và bắt được nhóm. Điều gì đã được chứng minh?',['Bắt cưỡng bức trước mọi đáp','Chỉ kết quả của chuỗi cụ thể này'],1,'Trình xem SGF kiểm tra đặt quân/bắt quân, không tìm đáp tối ưu. Biến bạn tự dựng cần người mạnh hoặc engine phân tích độc lập.');
q('dan3','estimate-range','Toàn bàn','Ước lượng có khoảng','Sau komi, đất chắc cho Đen−Trắng là +3. Một vùng chưa ổn định có thể thêm từ −8 đến +4. Khoảng kết quả là gì?',['−5 đến +7','+3 đến +7','Đen chắc thắng 3'],0,'Cộng khoảng: 3−8=−5 và 3+4=7. Còn khả năng thua nên phải giải quyết vùng chưa ổn định.',opening);
q('dan3','independent-proof','Đọc biến','Kiểm tra lời giải tự viết','Bạn đã đọc A→B→C rồi nhớ chuỗi đó. Lần ôn kế tiếp, để kiểm tra thực sự hiểu, nên làm gì?',['Chép lại chuỗi ngay','Giấu lời giải, xét các đáp khác và tìm phản bác'],1,'Khả năng tái hiện một biến khác khả năng kiểm tra mọi đáp. Ghi nước phản bác mạnh nhất và điều kiện áp dụng.');
q('dan3','rank3-evidence','Thực chiến','Bằng chứng mục tiêu 3 dan','Bạn đạt 10/10 kiểm tra trong mục tiêu 3 dan. Điều nào hợp lý?',['App chứng nhận tôi là 3 dan','Tôi làm đúng mẫu câu này; cần rating thực chiến để đánh giá sức chơi'],1,'Bài kiểm tra không được hiệu chuẩn theo người chơi 3 dan. Không suy đẳng từ điểm nội dung hoặc số bài hoàn thành.');

export {questions};
export function stageForDepth(depth) { return depth === 1 ? 'foundation' : depth === 3 ? 'tactics' : depth === 5 ? 'reading' : depth === 7 ? 'strategy' : 'dan'; }
export function buildBank(readingBank) {
  return [...readingBank.map((p,i)=>({
    ...p,id:p.id,kind:'reading',stage:p.goal==='eyes'?(p.depth===1?'tactics':p.depth===3?'reading':p.depth===5?'strategy':'dan'):stageForDepth(p.depth),topic:p.shape==='tactical'?'Đọc biến':'Sống/chết',
    title:p.goal==='eyes'?`Tạo hai mắt · ${i+1}`:p.shape==='tactical'?`Đọc bắt quân · ${i+1}`:`Phá không gian mắt · ${i+1}`,
    prompt:p.goal==='eyes'?`Đen đi trước. Tạo hai mắt thật riêng cho nhóm đen có dấu tam giác trong tối đa ${Math.ceil(p.depth/2)} lượt đen (${p.depth} lượt cả hai bên). Trắng được đáp ở mọi điểm hợp lệ hoặc bỏ lượt.`:`Đen đi trước. Bắt nhóm trắng có dấu tam giác trong tối đa ${Math.ceil(p.depth/2)} lượt đen (${p.depth} lượt cả hai bên). Trắng có thể đáp ở mọi điểm hợp lệ hoặc bỏ lượt.`,
    explanation:p.goal==='eyes'?'Mục tiêu là hai điểm trống riêng, mỗi điểm chỉ giáp quân của cùng nhóm đen được đánh dấu. Đây là điều kiện đủ để nhóm sống dưới luật cấm tự sát. Bộ đọc xét tất cả đáp hợp lệ trong giới hạn lượt; không đánh giá sức chơi toàn bàn.':'Mọi nước đặt quân hợp lệ của hai bên và bỏ lượt của trắng được xét trên toàn bộ bàn bài tập, dưới positional superko. Đây là bài bắt có thời hạn; không phân tích ko toàn bàn 19×19 và không hiệu chuẩn rank.'
  })),...questions];
}
