const beginner = [
 {title:'Nước đi đầu tiên',heading:'Đặt quân trên giao điểm',description:'Bạn cầm quân đen. Chạm vào một giao điểm bất kỳ trên bàn. Quân nằm ở chỗ hai đường gặp nhau, không nằm trong ô vuông.',tip:'Đen đi trước. Hai bên luân phiên đặt một quân. Quân đã đặt không di chuyển.',kind:'place'},
 {title:'Đếm khí',heading:'Quân cờ cần có khí',description:'Quân đen ở giữa bàn. Chạm vào nó để thấy các khí, rồi chọn số khí của quân này.',tip:'Chỉ đếm giao điểm trống sát bên theo ngang và dọc. Đường chéo không phải là khí.',kind:'count',setup:[[12,1]],answer:4},
 {title:'Bắt một quân',heading:'Lấp khí cuối cùng',description:'Quân trắng chỉ còn một khí. Đặt quân đen vào khí cuối cùng để bắt quân trắng.',tip:'Khi không còn khí, quân hoặc cả nhóm quân bị nhấc khỏi bàn.',kind:'capture',setup:[[12,2],[7,1],[11,1],[13,1]],target:17},
 {title:'Bắt cả nhóm',heading:'Nối liền, cùng sống',description:'Hai quân trắng nối với nhau theo đường ngang. Tìm khí cuối cùng và bắt cả nhóm bằng một nước đen.',tip:'Các quân cùng màu nối ngang hoặc dọc dùng chung khí. Nối chéo chưa tạo thành nhóm.',kind:'capture',setup:[[11,2],[12,2],[6,1],[7,1],[10,1],[13,1],[16,1]],target:17},
 {title:'Cứu quân của bạn',heading:'Thoát khỏi atari',description:'Quân đen chỉ còn một khí — tình huống này gọi là atari. Nối thêm một quân vào khí cuối để nhóm có nhiều khí hơn.',tip:'Trước khi đi, hãy nhìn nhóm nào chỉ còn một khí. Bắt đối phương hoặc nối ra ngoài có thể cứu nhóm.',kind:'save',setup:[[12,1],[7,2],[11,2],[13,2]],target:17},
 {title:'Bao vây đất',heading:'Điểm đến từ đâu?',description:'Đen đã bao quanh vùng trống giữa bàn. Có bao nhiêu giao điểm trống thuộc vùng này? Chọn câu trả lời bên dưới.',tip:'Trong cách đếm diện tích, điểm = quân sống trên bàn + vùng trống chỉ giáp quân của mình. Trắng được cộng komi để bù việc đi sau.',kind:'territory',setup:[[6,1],[7,1],[8,1],[11,1],[13,1],[16,1],[17,1],[18,1],[0,2],[4,2],[20,2],[24,2]],answer:1}
];
export const levels = [{id:"beginner",name:"Nhập môn",summary:"Luật cơ bản · 6 bài"},{id:"intermediate",name:"Trung cấp",summary:"Hình cờ và chiến thuật · 6 bài"},{id:"advanced",name:"Nâng cao",summary:"Đọc biến và quyết định · 6 bài"}];
export const lessons = beginner.map((l,i)=>({...l,id:`beginner-${i}`,level:"beginner"}));
const intermediate = [
 {title:'Nối trước khi bị cắt',heading:'Giữ hai nhóm liên lạc',description:'Hai quân đen nằm hai bên một điểm cắt. Nối trực tiếp chúng thành một nhóm.',tip:'Nối quân giúp chia sẻ khí. Trước khi tấn công, kiểm tra điểm cắt trong hình cờ của mình.',kind:'tactic',setup:[[11,1],[13,1],[7,2],[17,2]],target:12,success:'Đúng! Hai quân đã trở thành một nhóm, dùng chung khí.',hint:'Điểm giữa hai quân đen nối chúng theo đường ngang.'},
 {title:'Cắt liên lạc',heading:'Tách hai quân trắng',description:'Trắng có hai quân cách nhau một giao điểm. Đen chiếm điểm nối để ngăn trắng nối trực tiếp.',tip:'Cắt chỉ có ích khi quân cắt có thể sống hoặc tạo lợi ích khác. Kiểm tra khí sau khi cắt.',kind:'tactic',setup:[[11,2],[13,2],[7,1],[17,1]],target:12,success:'Đen đã chiếm điểm nối. Hai quân trắng vẫn là hai nhóm riêng.',hint:'Chiếm giao điểm giữa hai quân trắng.'},
 {title:'Atari kép',heading:'Một nước, hai đe dọa',description:'Đặt một quân đen để cùng lúc đưa hai nhóm trắng vào atari. Chạm quân trắng để kiểm tra khí.',tip:'Atari kép có thể buộc đối phương chọn nhóm cần cứu. Luôn đọc xem đối phương có nước bắt quân hoặc nối cả hai nhóm không.',kind:'tactic',setup:[[11,2],[13,2],[6,1],[10,1],[8,1],[14,1]],target:12,success:'Đúng! Hai nhóm trắng mỗi nhóm chỉ còn 1 khí: B2 và D2.',hint:'Khí chung của hai quân trắng là điểm tạo atari kép.'},
 {title:'Tạo hai mắt',heading:'Chia không gian mắt',description:'Đen có một khoảng trống ba điểm ở góc trên trái. Đặt quân ở điểm giữa để chia thành hai mắt riêng.',tip:'Hai mắt thật riêng biệt bảo vệ một nhóm khỏi bị bắt theo luật cấm tự sát. Hai điểm trống liền nhau chưa phải hai mắt.',kind:'tactic',setup:[[3,1],[5,1],[6,1],[7,1],[8,1]],target:1,success:'Đúng! A5 và C5 là hai mắt riêng. Trắng không thể đi vào một trong hai điểm này.',hint:'Đặt ở B5, chia khoảng trống A5–C5 thành hai phần.'},
 {title:'Đọc khí của nhóm',heading:'Không đếm trùng khí',description:'Ba quân đen nối thành một nhóm. Có bao nhiêu khí khác nhau? Chạm một quân đen để xem cả nhóm.',tip:'Một giao điểm trống cạnh hai quân trong cùng nhóm vẫn chỉ là một khí.',kind:'quiz',setup:[[6,1],[7,1],[11,1],[1,2],[10,2]],choices:['4 khí','5 khí','6 khí','7 khí'],answer:1,success:'Đúng: 5 khí tại A4, D4, C5, C3 và B2. Điểm C3 chỉ đếm một lần dù cạnh hai quân đen.',hint:'Đếm các điểm trống quanh cả nhóm, mỗi điểm đúng một lần.'},
 {title:'Nhận diện ko',heading:'Bắt lại ngay có hợp lệ?',description:'Đen vừa bắt tại C3. Trắng muốn bắt lại ở C4, tái tạo đúng thế bàn trước đó. Trắng được bắt lại ngay không?',tip:'App dùng positional superko: nước đặt quân không được tái tạo một thế bàn đã xuất hiện. Bỏ lượt vẫn hợp lệ.',kind:'quiz',setup:[[2,1],[6,1],[8,1],[12,1],[11,2],[13,2],[17,2]],choices:['Được, vì đây là bắt quân','Không, vì lặp lại thế bàn'],answer:1,success:'Đúng. Trắng phải tạo thay đổi ở nơi khác trước khi quay lại ko; còn phải kiểm tra toàn bộ lịch sử bàn.',hint:'Nước bắt lại tái tạo đúng thế trước nước đen C3.'}
];
const advanced = [
 {title:'Snapback: hy sinh để bắt',heading:'Đọc qua nước mất quân',description:'Tìm nước hy sinh một quân ở góc trên phải. Sau khi trắng bắt quân đó, tìm nước bắt ngược nhóm trắng. Đây là biến minh họa; trắng không bắt buộc chọn nước đáp này.',tip:'Snapback khác ko: nước bắt ngược lấy nhiều quân và không lặp thế bàn. Đọc cả nước đáp, không dừng ở việc mất một quân.',kind:'sequence',setup:[[3,2],[8,1],[13,1],[14,2],[19,1]],lines:[[4,9,4]],success:'Đúng! Hy sinh 1 quân ở E5, rồi bắt ngược 2 quân trắng E4–E3. Thế bàn mới không lặp lại.',hint:'Đi E5; sau khi trắng bắt ở E4, đặt lại E5.'},
 {title:'Chuyển hóa atari kép',heading:'Đọc nước cứu và nước bắt',description:'Tạo atari kép. Trắng trong biến này cứu quân bên trái. Bạn phải bắt nhóm còn lại. Bài tập luyện một biến cụ thể, không đánh giá toàn bộ lựa chọn của trắng.',tip:'Sau khi đối phương đáp, đọc lại khí. Kế hoạch ban đầu phải khớp với thế bàn mới.',kind:'sequence',setup:[[11,2],[13,2],[6,1],[10,1],[8,1],[14,1]],lines:[[12,16,18]],success:'Đúng! C3 tạo atari kép; trắng cứu B3 bằng B2; đen D2 bắt quân D3.',hint:'C3 → trắng B2 → đen D2.'},
 {title:'Đọc bẫy ở biên',heading:'Hai cách ép cùng mục tiêu',description:'Quân trắng B5 có hai khí. Chọn A5 hoặc C5 để ép, đọc nước đáp rồi bắt. Nếu trắng không thể nối, biến sẽ cho trắng đi nơi khác.',tip:'Gần biên, số đường thoát giảm. Kiểm tra cả nối dài và nước tự sát trước khi kết luận một nhóm thoát được.',kind:'sequence',setup:[[1,2],[3,1],[6,1],[7,1]],lines:[[2,0,5],[0,24,2]],success:'Đã đọc xong biến: nhóm trắng ở biên bị bắt. Bài chỉ minh họa các nước đáp đã ghi, chưa chứng minh mọi biến phòng thủ.',hint:'C5 → trắng A5 → đen A4; hoặc A5 → trắng E1 → đen C5.'},
 {title:'Chọn đe dọa ko',heading:'Đối phương có thể bỏ qua?',description:'Bạn muốn lấy lại ko. Có hai nước ở nơi khác: A đe dọa bắt nhóm lớn hơn giá trị ko nếu bị bỏ qua; B không tạo tổn thất đáng kể. Khi các điều kiện khác như nhau, chọn nước nào?',tip:'Giá trị đe dọa phụ thuộc vào tổn thất khi bị bỏ qua, giá trị ko và số đe dọa hai bên. Một nước atari nhỏ không tự động là đe dọa đủ lớn.',kind:'quiz',setup:[[2,1],[6,1],[8,1],[12,1],[11,2],[13,2],[17,2]],choices:['A: đe dọa tổn thất lớn','B: nước không có hậu quả'],answer:0,success:'A là lựa chọn phù hợp với giả định. Nó buộc đối phương cân nhắc giữa đáp đe dọa và giữ ko.',hint:'So sánh thiệt hại nếu đối phương bỏ qua, không chỉ hình dạng nước đi.'},
 {title:'Seki: sống chung',heading:'Hai mắt có phải bắt buộc?',description:'Trong một thế seki đã được đọc xác nhận, mỗi bên sẽ bị bắt nếu tự lấp khí chung trước. Nhóm chưa có hai mắt có thể sống không?',tip:'Seki là sống chung do cân bằng khí. Phải đọc cụ thể; chỉ nhìn hai nhóm có khí chung chưa đủ kết luận seki.',kind:'quiz',setup:[],choices:['Không: mọi nhóm sống đều cần hai mắt','Có: seki là một ngoại lệ'],answer:1,success:'Đúng. Hai mắt là điều kiện đủ phổ biến, không phải điều kiện bắt buộc cho mọi nhóm sống.',hint:'Trong giả định của câu hỏi, bên đi vào khí chung trước sẽ thua cuộc đua bắt.'},
 {title:'Quan tử: giữ tiên thủ',heading:'So sánh cả nước tiếp theo',description:'Giả định: A lấy 8 điểm nhưng mất lượt chủ động. B lấy 5 điểm, buộc đối phương đáp, rồi bạn lấy thêm 6 điểm ở nơi khác. Cả hai biến đều an toàn và điểm không chồng lấp. Biến nào hơn?',tip:'Tiên thủ (sente) là giữ quyền chọn điểm lớn tiếp theo vì đối phương cần đáp. Hậu thủ (gote) nhường quyền chủ động. Định giá thực tế phụ thuộc toàn bàn.',kind:'quiz',setup:[],choices:['A: tổng 8 điểm','B: tổng 11 điểm'],answer:1,success:'Theo giả định: B được 5 + 6 = 11, hơn A 3 điểm. Đây là bài so sánh biến, không phải quy tắc cứ sente là tốt hơn.',hint:'Cộng lợi ích không chồng lấp của toàn bộ chuỗi.'}
];
for (const [level, items] of [['intermediate',intermediate],['advanced',advanced]]) {
  lessons.push(...items.map((l,i)=>({...l,id:`${level}-${i}`,level})));
}
